name: Build and Push Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v5

      - id: extract_version
        run: |
          version=$(grep -Eo 'kubectl:\S+' Dockerfile | sed -E 's/kubectl://')
          echo "kubectl_version=$version" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/nrlulz/kubectl:${{ steps.extract_version.outputs.kubectl_version }}
